# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='link',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
