# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_usertoken'),
        ('links', '0002_auto_20170424_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(db_index=True),
        ),
    ]
